### ISSUE TITLE
Jiggler code is way overly complex

### ISSUE THREAD

**Issue by Jax121243** [FalsePhilosopher/badusb#17]
Just wanna let you know that the jiggler code could be much cleaner using REPEAT.
for example:

```
DEFAULT_DELAY 240000
REM repeatedly press CTRL using repeat
CTRL
REPEAT 99999
```

And yes, this code is all duckyscript 1.0, I've used repeat before on fz and it works well.

**Comment by FalsePhilosopher** [comment]
Feel free to submit a PR to add whatever version you feel like.
