### ISSUE TITLE
badusb delete system32 no working

### ISSUE THREAD

**Issue by matias1233218** [FalsePhilosopher/badusb#21]
out of curiosity I wanted to use the "delete system32" script on my computer which I was going to format anyway, but I realized that the script either because of the windows version or something else does not work, it results in "access denied " in cmd, and that is if it runs well, because it gets stuck in the administrator confirmation dialog
![image](https://github.com/user-attachments/assets/6b7008cf-b7bc-4ad8-8e6f-4a6b9db5c185)

**Comment by FalsePhilosopher** [comment]
Show the error that is produced right after the text string gets entered, it's more then likely a formatting error with your keyboard layout.
